export const BULK_QUESTIONS = [
  { questionText: 'Who won the 2022 FIFA World Cup?', options: ['France', 'Argentina', 'Brazil', 'Germany'], correctAnswer: 1, category: 'Football' },
  { questionText: 'Which club has won the most Champions League titles?', options: ['AC Milan', 'Liverpool', 'Real Madrid', 'Bayern Munich'], correctAnswer: 2, category: 'Football' },
  { questionText: 'Who is the all-time top scorer in international football?', options: ['Lionel Messi', 'Cristiano Ronaldo', 'Ali Daei', 'Pelé'], correctAnswer: 1, category: 'Football' },
  { questionText: 'Which country hosted the first ever World Cup in 1930?', options: ['Brazil', 'Italy', 'Uruguay', 'Argentina'], correctAnswer: 2, category: 'Football' },
  { questionText: 'Which player is known as "The King"?', options: ['Maradona', 'Pelé', 'Cruyff', 'Zidane'], correctAnswer: 1, category: 'Football' },
  { questionText: 'Who won the 1966 World Cup?', options: ['Germany', 'England', 'Brazil', 'Argentina'], correctAnswer: 1, category: 'Football' },
  { questionText: 'Which club is known as "The Old Lady"?', options: ['Inter Milan', 'Juventus', 'AC Milan', 'Roma'], correctAnswer: 1, category: 'Football' },
  { questionText: 'Who is the manager of Manchester City?', options: ['Jurgen Klopp', 'Pep Guardiola', 'Jose Mourinho', 'Carlo Ancelotti'], correctAnswer: 1, category: 'Football' },
  { questionText: 'Which stadium is known as "The Theatre of Dreams"?', options: ['Anfield', 'Old Trafford', 'Camp Nou', 'San Siro'], correctAnswer: 1, category: 'Football' },
  { questionText: 'Who won the Ballon d\'Or in 2023?', options: ['Erling Haaland', 'Lionel Messi', 'Kylian Mbappé', 'Kevin De Bruyne'], correctAnswer: 1, category: 'Football' },
  { questionText: 'Who was the first President of the United States?', options: ['Thomas Jefferson', 'George Washington', 'John Adams', 'Benjamin Franklin'], correctAnswer: 1, category: 'History' },
  { questionText: 'In which year did the Titanic sink?', options: ['1910', '1912', '1914', '1916'], correctAnswer: 1, category: 'History' },
  { questionText: 'Who was the leader of Nazi Germany during WWII?', options: ['Joseph Stalin', 'Benito Mussolini', 'Adolf Hitler', 'Winston Churchill'], correctAnswer: 2, category: 'History' },
  { questionText: 'Which empire was ruled by Julius Caesar?', options: ['Greek', 'Roman', 'Egyptian', 'Persian'], correctAnswer: 1, category: 'History' },
  { questionText: 'Who discovered America?', options: ['Christopher Columbus', 'Vasco da Gama', 'Ferdinand Magellan', 'Marco Polo'], correctAnswer: 0, category: 'History' },
  { questionText: 'What was the name of the ship that carried the Pilgrims to America?', options: ['Santa Maria', 'Mayflower', 'Pinta', 'Nina'], correctAnswer: 1, category: 'History' },
  { questionText: 'Who was the British Prime Minister during WWII?', options: ['Neville Chamberlain', 'Winston Churchill', 'Clement Attlee', 'Anthony Eden'], correctAnswer: 1, category: 'History' },
  { questionText: 'Which war was fought between the North and South in the USA?', options: ['Revolutionary War', 'Civil War', 'World War I', 'World War II'], correctAnswer: 1, category: 'History' },
  { questionText: 'Who was the first woman to fly solo across the Atlantic?', options: ['Amelia Earhart', 'Bessie Coleman', 'Harriet Quimby', 'Jacqueline Cochran'], correctAnswer: 0, category: 'History' },
  { questionText: 'What year did the Berlin Wall fall?', options: ['1987', '1989', '1991', '1993'], correctAnswer: 1, category: 'History' },
  { questionText: 'What is the capital of France?', options: ['London', 'Berlin', 'Madrid', 'Paris'], correctAnswer: 3, category: 'Geography' },
  { questionText: 'Which is the largest continent by area?', options: ['Africa', 'North America', 'Asia', 'Europe'], correctAnswer: 2, category: 'Geography' },
  { questionText: 'Which river is the longest in the world?', options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], correctAnswer: 1, category: 'Geography' },
  { questionText: 'What is the smallest country in the world?', options: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'], correctAnswer: 1, category: 'Geography' },
  { questionText: 'Which ocean is the largest?', options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], correctAnswer: 3, category: 'Geography' },
  { questionText: 'Which country has the most islands?', options: ['Canada', 'Norway', 'Sweden', 'Finland'], correctAnswer: 2, category: 'Geography' },
  { questionText: 'What is the capital of Japan?', options: ['Seoul', 'Beijing', 'Tokyo', 'Bangkok'], correctAnswer: 2, category: 'Geography' },
  { questionText: 'Which mountain is the highest in the world?', options: ['K2', 'Kangchenjunga', 'Mount Everest', 'Lhotse'], correctAnswer: 2, category: 'Geography' },
  { questionText: 'Which country is known as the Land of the Rising Sun?', options: ['China', 'South Korea', 'Japan', 'Thailand'], correctAnswer: 2, category: 'Geography' },
  { questionText: 'What is the capital of Australia?', options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'], correctAnswer: 2, category: 'Geography' },
  { questionText: 'What is the chemical symbol for water?', options: ['Wa', 'H2O', 'O2', 'CO2'], correctAnswer: 1, category: 'Science' },
  { questionText: 'Which planet is known as the Red Planet?', options: ['Venus', 'Mars', 'Jupiter', 'Saturn'], correctAnswer: 1, category: 'Science' },
  { questionText: 'What is the powerhouse of the cell?', options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi apparatus'], correctAnswer: 2, category: 'Science' },
  { questionText: 'Who proposed the theory of relativity?', options: ['Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Nikola Tesla'], correctAnswer: 1, category: 'Science' },
  { questionText: 'What is the hardest natural substance on Earth?', options: ['Gold', 'Iron', 'Diamond', 'Quartz'], correctAnswer: 2, category: 'Science' },
  { questionText: 'What is the most abundant gas in Earth\'s atmosphere?', options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen'], correctAnswer: 2, category: 'Science' },
  { questionText: 'What is the speed of light?', options: ['300,000 km/s', '150,000 km/s', '1,000,000 km/s', '50,000 km/s'], correctAnswer: 0, category: 'Science' },
  { questionText: 'Which planet is the largest in our solar system?', options: ['Earth', 'Mars', 'Jupiter', 'Saturn'], correctAnswer: 2, category: 'Science' },
  { questionText: 'What is the study of living organisms called?', options: ['Physics', 'Chemistry', 'Biology', 'Geology'], correctAnswer: 2, category: 'Science' },
  { questionText: 'What is the boiling point of water in Celsius?', options: ['50', '80', '100', '120'], correctAnswer: 2, category: 'Science' },
  { questionText: 'Who wrote "Sherlock Holmes"?', options: ['Agatha Christie', 'Arthur Conan Doyle', 'Edgar Allan Poe', 'Stephen King'], correctAnswer: 1, category: 'Mystery' },
  { questionText: 'What is the name of the detective in "Murder on the Orient Express"?', options: ['Hercule Poirot', 'Miss Marple', 'Sherlock Holmes', 'Nancy Drew'], correctAnswer: 0, category: 'Mystery' },
  { questionText: 'Which famous mystery writer is known as the "Queen of Crime"?', options: ['Agatha Christie', 'J.K. Rowling', 'Mary Higgins Clark', 'Gillian Flynn'], correctAnswer: 0, category: 'Mystery' },
  { questionText: 'What is the name of the fictional detective created by Edgar Allan Poe?', options: ['C. Auguste Dupin', 'Sherlock Holmes', 'Hercule Poirot', 'Miss Marple'], correctAnswer: 0, category: 'Mystery' },
  { questionText: 'Which novel is about a mysterious island?', options: ['Treasure Island', 'The Island of Dr. Moreau', 'Lord of the Flies', 'All of the above'], correctAnswer: 3, category: 'Mystery' },
  { questionText: 'What is a common theme in mystery novels?', options: ['Love', 'Crime', 'Comedy', 'Fantasy'], correctAnswer: 1, category: 'Mystery' },
  { questionText: 'Who is the author of "The Da Vinci Code"?', options: ['Dan Brown', 'Stephen King', 'J.K. Rowling', 'Agatha Christie'], correctAnswer: 0, category: 'Mystery' },
  { questionText: 'What is a "whodunit"?', options: ['A comedy', 'A mystery story', 'A horror story', 'A romance story'], correctAnswer: 1, category: 'Mystery' },
  { questionText: 'Which character is a famous fictional detective?', options: ['Harry Potter', 'Sherlock Holmes', 'Frodo Baggins', 'Katniss Everdeen'], correctAnswer: 1, category: 'Mystery' },
  { questionText: 'What is a common element in a mystery story?', options: ['A clue', 'A detective', 'A suspect', 'All of the above'], correctAnswer: 3, category: 'Mystery' }
];
